services:
  - type: web
    name: task-manager
    env: docker
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:e9iVfBSoG9uca+bOKIMZ2eIhpe/uhWPpC5UGPqB3A2w=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
      - key: PORT
        value: 8000
    healthCheckPath: /