services:
  - type: web
    name: task-manager
    runtime: php
    repo: https://github.com/Andoryukun27/task-manager
    branch: master
    buildCommand: |
      composer install
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: PORT
        value: 10000
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:e9iVfBSoG9uca+bOKIMZ2eIhpe/uhWPpC5UGPqB3A2w=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
